trigger: none

# Manual trigger only

variables:
  - group: CommonVariables

parameters:
  - name: Version
    displayName: 'Version'
    type: string

# get artifacts from pipeline build

resources:
  pipelines:
    - pipeline: build
      source: KeyVaultExplorer-Build
      trigger: none

steps:
  - download: build
    displayName: 'Download release notes artifact ⬇'
    artifact: 'macos'
  - download: build
    displayName: 'Download Windows artifacts ⬇'
    artifact: 'windows-msi'
  - script: |
      cp $(Agent.BuildDirectory)/build/macos/* $(Build.ArtifactStagingDirectory)/
      cp $(Agent.BuildDirectory)/build/windows-msi/* $(Build.ArtifactStagingDirectory)/
  - task: GitHubRelease@1
    displayName: 'Upload release notes to GitHub Release ⬆'
    inputs:
      gitHubConnection: 'angpysha'
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'userSpecifiedTag'
      tag: '${{ parameters.Version }}'
      addChangeLog: false
 # Upload artifact to github release

